{
 "title": "WX200 Weather Station",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "direction_offset", "query": "20" },
   { "name": "baro_altitude", "label": "Barometer Altitude (in feet)", "query": "5882.5" }
  ]
 },
 "panels": [
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wx200_temperature*(9/5)+32", "legendFormat": "{{location}}" },
    { "expr": "wx200_wind_chill*(9/5)+32", "legendFormat": "Wind Chill" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    { "expr": "wx200_temperature*(9/5)+32", "legendFormat": "{{location}}" },
    { "expr": "wx200_wind_chill*(9/5)+32", "legendFormat": "chill" }
   ]
  },
  {
   "title": "Humidity",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wx200_humidity", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "wx200_humidity", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wx200_pressure{location=\"local\"} * 0.02953",
     "legendFormat": "Local"
    },
    {
     "expr": "(wx200_pressure{location=\"local\"} * 0.02953)/(((288-(0.0065*$baro_altitude*0.3048))/288)^5.2561)",
     "legendFormat": "Corrected"
    }
   ]
  },
  {
   "title": "Change",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(delta(wx200_pressure{location=\"local\"}[1h]) * 0.02953)/(((288-(0.0065*$baro_altitude*0.3048))/288)^5.2561)",
     "legendFormat": "1h"
    },
    {
     "expr": "(delta(wx200_pressure{location=\"local\"}[3h]) * 0.02953)/(((288-(0.0065*$baro_altitude*0.3048))/288)^5.2561)",
     "legendFormat": "3h"
    },
    { "expr": "changes" }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "pressurehg" }
   ],
   "targets": [
    {
     "expr": "(wx200_pressure{location=\"local\"} * 0.02953)/(((288-(0.0065*$baro_altitude*0.3048))/288)^5.2561)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wx200_dew_point*(9/5)+32", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Dew Point",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    { "expr": "wx200_dew_point*(9/5)+32", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wx200_avg_wind_direction+$direction_offset"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    { "expr": "wx200_gust_speed*2.23694", "legendFormat": "Gust" },
    { "expr": "wx200_avg_wind_speed*2.23694", "legendFormat": "Avg" }
   ]
  },
  {
   "title": "Rain",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "inches" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(wx200_rain_total[5m])*0.0393701 * 12",
     "legendFormat": "Current Rate"
    },
    {
     "expr": "increase(wx200_rain_total[24h])*0.0393701",
     "legendFormat": "Total Last 24h"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "inches" } },
   "yaxes": [
    { "format": "in" }
   ],
   "targets": [
    {
     "expr": "increase(wx200_rain_total[$__interval])*0.0393701",
     "legendFormat": "inches"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wx200_gust_speed*2.23694", "legendFormat": "Gusts" },
    { "expr": "wx200_avg_wind_speed*2.23694", "legendFormat": "Average" }
   ]
  }
 ]
}